trigger:
  batch: true
  branches:
    include:
    - master
    - release/*
  paths:
    exclude:
    - README.md

pr:
  branches:
    include:
    - master
    - release/*

variables:
  SolutionFile: 'src/StreamJsonRpcMessagePack.sln'
  CommonBuildOptions: '-nologo --verbosity:quiet -p:Platform=AnyCPU --configuration Release'

jobs:
- job: build

  # vs2017 because the job needs .NET Framework SDK 4.6.1 and 4.7.1.
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: PowerShell@2
    displayName: 'Set Variables'
    inputs:
      targetType: 'filePath'
      failOnStderr: true
      filePath: '$(Build.SourcesDirectory)/build/SetAzurePipelineVariables.ps1'

  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk 3.0.100'
    inputs:
      version: 3.0.100

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore
      projects: '$(SolutionFile)'
      verbosityRestore: Quiet

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      projects: '$(SolutionFile)'
      arguments: '$(CommonBuildOptions)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      projects: src/JsonRpcMessagePackFormatter.Test/JsonRpcMessagePackFormatter.Test.csproj
      arguments: '$(CommonBuildOptions)'

  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet 4.9.2'
    inputs:
      versionSpec: 4.9.2

  - task: NuGetCommand@2
    displayName: 'NuGet custom'
    inputs:
      command: custom
      arguments: 'pack -Verbosity quiet -ForceEnglishOutput -Version $(PackageVersion) -BasePath bin/JsonRpcMessagePackFormatter/AnyCPU/Release -OutputDirectory bin/nupkg -Properties commitHash=$(Build.SourceVersion) build/nuspec/Asmichi.StreamJsonRpcMessagePack.nuspec'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: 'bin/nupkg/*'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'

